project:
  type: website
  output-dir: docs

website:
  title: "Madeline Berger"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resources.qmd
        text: Resources
      - href: CV/MBerger_CV.pdf
        text: CV
  

format:
  html:
    theme: minty
    css: styles.css
    toc: true



