project:
  type: website
  output-dir: docs

website:
  title: " "
  favicon: images/logos/green_burger.png
  navbar:
    title: Madeline Berger
    logo: images/logos/name_icon_giant.png
    right:
      - href: index.qmd
        text: Home
     # - href: resources.qmd
    #   text: Resources
      - href: posts.qmd
        text: Portfolio
      - href: CV/CV_01_2025_MBerger.pdf
        text: CV
        menu:
        - text: English
          href: CV/CV_Spanish.pdf
          target: _blank
        - text: Español
          href: CV/MBerger_CV_Spanish.pdf
          target: _blank
  page-footer: 
    background: light
    left: 
      - "Copyright 2022, Madeline Berger"
    right: 
      - icon: github
        href: https://github.com/madelinemberger
      - icon: linkedin
       href: https://www.linkedin.com/in/madeline-berger-a803a27a
  

format:
  html:
    theme: minty
    css: styles.css
    toc: false
    

preview:
  browser: true


